[package]
name = "minigrep"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39.3", features = ["rt", "rt-multi-thread", "macros"] }
reqwest = "0.12.7"
base64 = "0.22.1"
regex = "1.10.6"
